language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_github hadley/testthat hadley/purrr"
- "./travis-tool.sh install_r robertzk/testthatsomemore"
- "./travis-tool.sh github_package jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: ODHKOmZxBiiZPPsuBCcngZD+QKXHfEll1kpJCyB6ZAifEGwntYy3eS5XYfD3df8fH4OCUPpXQc3pLyX4oudP2UvXW5cu16F14ZW6zyD/WV0pfh2dbNmB2YmWwvD7nLkHcSAUuJl7TN7q8Uwmjox84fxYRXrk0f2EdMd+GHbw9QM=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
