language: r
r_packages:
  - testthat
r_github_packages:
  - robertzk/testthatsomemore
  - hadley/purrr
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: ODHKOmZxBiiZPPsuBCcngZD+QKXHfEll1kpJCyB6ZAifEGwntYy3eS5XYfD3df8fH4OCUPpXQc3pLyX4oudP2UvXW5cu16F14ZW6zyD/WV0pfh2dbNmB2YmWwvD7nLkHcSAUuJl7TN7q8Uwmjox84fxYRXrk0f2EdMd+GHbw9QM=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
